plugins { id 'com.android.application' }

android {
    namespace 'com.noaaweatherdash'
    compileSdk 35

    defaultConfig {
        applicationId 'com.noaaweatherdash.android'
        minSdk 26
        targetSdk 35
        versionCode 6
        versionName '2.0.6'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
